### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by bortzmeyer** [AGProjects/python-gnutls#12]
There have been already issues open for a port to Python 3 (#2 and #5) but they were closed without a real explanation.
Is there a plan to port to Python 3? If not, the library could be considered dead since Python 2 is soon to become unmaintained https://pythoninsider.blogspot.com/2019/10/python-2717-released.html

**Comment by adigeo** [comment]
The short answer is yes, we do have plans to port it.

**Comment by danpascu** [comment]
Patches are welcome.

**Comment by hughsie** [comment]
The new https://github.com/hughsie/PyGnuTLS is Python 3 only. I'm planning to clean up the fork some more and then submit it to PyPI when API stable.

**Comment by adigeo** [comment]
See https://github.com/AGProjects/python3-gnutls
