### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by bortzmeyer** [AGProjects/python-gnutls#13]
As far as I know, there is zero documentation for this library, except a few samples in `examples/`. Did I search in the wrong place, or is it something to address?

**Comment by danpascu** [comment]
It is something to address. Patches are welcome.

**Comment by hughsie** [comment]
Hi @bortzmeyer -- I wanted to let you know I've forked python-gnutls -- the new https://github.com/hughsie/PyGnuTLS is under the same licence as before (LGPLv2+) of course, but it's now Python 3 only. I'm adding documentation myself and reviewing pull requests so if you are using a private fork with your changes it would be great to merge them back into a common codebase. I'm planning to clean up the fork some more and then submit it to PyPI when API stable. Comments welcome!
