### ISSUE TITLE
Python 3.5 failure

### ISSUE THREAD

**Issue by leenaars** [AGProjects/python-gnutls#2]
While most recent versions of python-gnutls worked well with Py3k, there is now a build failure due to a syntax error. See on NixOS:

https://travis-ci.org/NixOS/nixpkgs/jobs/150302536 

Is it possible to fix this?

**Comment by saghul** [comment]
python-gnutls does not currently work on Python 3. It might have if you used 2to3, but I know there are a number of issues to be addressed for it to work properly. Patches are welcome, but beware, it might now be a small endeavor.

**Comment by leenaars** [comment]
hi @saghul, thanks for the quick reply. Good to know. I've marked it as py2 only.
